### ISSUE TITLE
IllegalArgumentException: Area already instantiated for: ProjectDefault (Template) 

### ISSUE THREAD

**Issue by landsman** [malliina/idea-sbt-executor#3]
Intellij Idea Ultimate 2019.2

```
java.lang.IllegalArgumentException: Area already instantiated for: ProjectDefault (Template) Project
	at com.intellij.openapi.extensions.Extensions.instantiateArea(Extensions.java:129)
	at com.intellij.openapi.project.impl.ProjectImpl.bootstrapPicoContainer(ProjectImpl.java:146)
	at com.intellij.openapi.project.impl.DefaultProject$1$1.init(DefaultProject.java:67)
	at com.intellij.openapi.project.impl.DefaultProject$1.init(DefaultProject.java:96)
	at com.intellij.openapi.project.impl.DefaultProjectTimed.get(DefaultProjectTimed.java:33)
	at com.intellij.openapi.project.impl.DefaultProject.getDelegate(DefaultProject.java:123)
	at com.intellij.openapi.project.impl.DefaultProject.getComponent(DefaultProject.java:213)
	at com.intellij.openapi.wm.ToolWindowManager.getInstance(ToolWindowManager.java:26)
	at com.mle.idea.sbtexecutor.SbtExecuteConsoleComponent.unregisterConsole(SbtExecuteConsoleComponent.scala:63)
	at com.mle.idea.sbtexecutor.SbtExecuteConsoleComponent.disposeComponent(SbtExecuteConsoleComponent.scala:99)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.disposeComponents(ComponentManagerImpl.java:185)
	at com.intellij.openapi.project.impl.ProjectImpl.dispose(ProjectImpl.java:323)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:48)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:44)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:135)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:104)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:214)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:104)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeAll(ObjectTree.java:162)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:137)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:133)
	at com.intellij.util.Timed.dispose(Timed.java:41)
	at com.intellij.util.TimedReference.dispose(TimedReference.java:22)
	at com.intellij.openapi.project.impl.DefaultProjectTimed.lambda$null$0(DefaultProjectTimed.java:47)
	at com.intellij.openapi.command.WriteCommandAction.lambda$runWriteCommandAction$5(WriteCommandAction.java:369)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl$1.run(WriteCommandAction.java:125)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
	at com.intellij.openapi.command.WriteCommandAction.lambda$null$1(WriteCommandAction.java:264)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1045)
	at com.intellij.openapi.command.WriteCommandAction.lambda$performWriteCommandAction$2(WriteCommandAction.java:263)
	at com.intellij.openapi.command.WriteCommandAction.lambda$doExecuteCommand$4(WriteCommandAction.java:320)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:188)
	at com.intellij.openapi.command.WriteCommandAction.doExecuteCommand(WriteCommandAction.java:322)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:263)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:245)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.run(WriteCommandAction.java:127)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:369)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:361)
	at com.intellij.openapi.project.impl.DefaultProjectTimed.lambda$dispose$1(DefaultProjectTimed.java:47)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:74)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:97)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:415)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:749)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by bbb3** [comment]
The same in 2019.2.3 just some lines has been changed:

**Comment by emonmishra** [comment]
is anyone working on this, please?

**Comment by mpujari** [comment]
> is anyone working on this, please?

Had same issue and searching through came across https://en.programqa.com/question/57679870/ 
So now have removed the plugin as we have build in support for sbt from **IntellIJ Scala Plugin** things are looking good.

**Comment by malliina** [comment]
Sorry, I'll try to get this plugin back on track soon or will remove it if it doesn't work. I haven't maintained this for a while. I'll report on any progress asap.

**Comment by malliina** [comment]
With the latest version (1.3.1) of the plugin I haven't been able to reproduce this issue with IntelliJ 2019.3.3.

**Comment by malliina** [comment]
As I haven't been able to reproduce with the latest version I'll close this.
